/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as OgRouteImport } from './app/og'
import { Route as JemRouteImport } from './app/jem'
import { Route as DesignRouteImport } from './app/design'
import { Route as BlogRouteImport } from './app/blog'
import { Route as IndexRouteImport } from './app/index'
import { Route as WebmarksIndexRouteImport } from './app/webmarks/index'
import { Route as BlogIndexRouteImport } from './app/blog/index'
import { Route as BlogSlugRouteImport } from './app/blog/$slug'
import { Route as BlogTagTagRouteImport } from './app/blog/tag/$tag'

const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const JemRoute = JemRouteImport.update({
  id: '/jem',
  path: '/jem',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebmarksIndexRoute = WebmarksIndexRouteImport.update({
  id: '/webmarks/',
  path: '/webmarks/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogTagTagRoute = BlogTagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/design': typeof DesignRoute
  '/jem': typeof JemRoute
  '/og': typeof OgRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/webmarks/': typeof WebmarksIndexRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/jem': typeof JemRoute
  '/og': typeof OgRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/webmarks': typeof WebmarksIndexRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/design': typeof DesignRoute
  '/jem': typeof JemRoute
  '/og': typeof OgRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/webmarks/': typeof WebmarksIndexRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/design'
    | '/jem'
    | '/og'
    | '/blog/$slug'
    | '/blog/'
    | '/webmarks/'
    | '/blog/tag/$tag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/jem'
    | '/og'
    | '/blog/$slug'
    | '/blog'
    | '/webmarks'
    | '/blog/tag/$tag'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/design'
    | '/jem'
    | '/og'
    | '/blog/$slug'
    | '/blog/'
    | '/webmarks/'
    | '/blog/tag/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  DesignRoute: typeof DesignRoute
  JemRoute: typeof JemRoute
  OgRoute: typeof OgRoute
  WebmarksIndexRoute: typeof WebmarksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jem': {
      id: '/jem'
      path: '/jem'
      fullPath: '/jem'
      preLoaderRoute: typeof JemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webmarks/': {
      id: '/webmarks/'
      path: '/webmarks'
      fullPath: '/webmarks/'
      preLoaderRoute: typeof WebmarksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/tag/$tag': {
      id: '/blog/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/blog/tag/$tag'
      preLoaderRoute: typeof BlogTagTagRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogTagTagRoute: typeof BlogTagTagRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogTagTagRoute: BlogTagTagRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  DesignRoute: DesignRoute,
  JemRoute: JemRoute,
  OgRoute: OgRoute,
  WebmarksIndexRoute: WebmarksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
